[tool.poetry]
name = "django-sorting-bootstrap"
version = "2.5.0"
description = "Sorting templates API using sorting, Django templatetags and Bootstrap classes."
authors = ["Thiago Carvalho D'Ávila <thiagocavila@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/staticdev/django-sorting-bootstrap"
homepage = "https://github.com/staticdev/django-sorting-bootstrap"
documentation = "https://django-sorting-bootstrap.readthedocs.io"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
Changelog = "https://github.com/staticdev/django-sorting-bootstrap/releases"

[tool.poetry.dependencies]
python = "^3.7"
django = ">=2.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.1.4"
safety = "^1.8.5"
pytest = "^6.0.0"
mypy = "^0.782"
reorder-python-imports = "^2.3.4"
pre-commit = "^2.6.0"
coverage = {extras = ["toml"], version = "^5.2"}
pytest-django = "^3.9.0"
pygments = "^2.6.1"
xdoctest = "^0.13.0"
sphinx = "^3.1.2"
sphinx-autobuild = "^0.7.1"
darglint = "^1.5.2"
flake8-docstrings = "^1.5.0"
flake8-rst-docstrings = "^0.0.13"
pep8-naming = "^0.11.1"
pre-commit-hooks = "^3.1.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["django_sorting_bootstrap"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
